4 get api reviews
uzair-haroon/be-nc-games-project pull request #3
Opened 2022-11-14 15:57 UTC by uzair-haroon

2022-11-14 17:38 UTC, dav3rid requested changes
A couple of minor alterations Uzair - I'm also a little concerned that the commits detailing the tests come after your implementations 🤔

2022-11-14 17:38 UTC, dav3rid commented on models/games-model.js
> +                INNER JOIN comments
Would opt for an alternative JOIN here to include any articles that do not have any associated articles

2022-11-14 17:38 UTC, dav3rid commented on __tests__/app.test.js
> +                        review_body: expect.any(String),
We shouldn't have a review body present on the responses here - you may (definitely will!) need to amend your model to reflect

2022-11-14 18:55 UTC, uzair-haroon commented
> A couple of minor alterations Uzair - I'm also a little concerned that the commits detailing the tests come after your implementations 🤔

Hi Dave, It was a commit mistake. I did the implementation in a TDD fashion, but I forgot to commit the test file with the controller and model code, so I had to do an extra commit after to include the tests.

2022-11-15 10:40 UTC, xViolaine approved these changes
Looks good, nice implementation of the former feedback - just make sure to delete the "app.use(express.json());" line, as this will not become relevant until a later point 👀

2022-11-15 10:40 UTC, xViolaine commented on app.js
>  app.use(express.json());
We do not need this line of code yet, so it should not be here

2022-11-15 10:43 UTC, merged